module.exports = {
  content: ["./frontend/index.html"],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#cfdce3",
        background: "#f7f9fb",
        "on-primary-container": "#455367",
        "surface-bright": "#f7f9fb",
        outline: "#717c82",
        "on-primary": "#f6f7ff",
        "on-tertiary": "#e9ffe5",
        "on-surface-variant": "#566166",
        "tertiary-container": "#dcfcd9",
        "surface-container-highest": "#d9e4ea",
        "on-tertiary-container": "#476248",
        "primary-dim": "#455368",
        tertiary: "#4a664b",
        primary: "#515f74",
        "on-secondary-container": "#445365",
        "surface-container": "#e8eff3",
        "primary-container": "#d5e3fd",
        "surface-container-high": "#e1e9ee",
        "inverse-primary": "#d5e3fd",
        "on-background": "#2a3439",
        "surface-container-low": "#f0f4f7",
        surface: "#f7f9fb",
        "on-surface": "#2a3439",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#a9b4b9",
        error: "#9f403d",
        "secondary-container": "#d4e4fa",
      },
      fontFamily: {
        sans: ["-apple-system", "PingFang SC", "Noto Sans SC", "Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
