module.exports = {
  content: ["./frontend/index.html", "./frontend/js/**/*.js"],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d7e2e2",
        background: "#f7faf9",
        "on-primary-container": "#0b5f5d",
        "surface-bright": "#fbfdfc",
        outline: "#748083",
        "on-primary": "#f8fffe",
        "on-tertiary": "#effcf5",
        "on-surface-variant": "#536171",
        "tertiary-container": "#d9f6e8",
        "surface-container-highest": "#dfeaea",
        "on-tertiary-container": "#2d664d",
        "primary-dim": "#0a7776",
        tertiary: "#24a876",
        primary: "#0e8f8d",
        "on-secondary-container": "#375063",
        "surface-container": "#eaf2f2",
        "primary-container": "#e1f4f3",
        "surface-container-high": "#e5eeee",
        "inverse-primary": "#bfeeed",
        "on-background": "#253443",
        "surface-container-low": "#f1f6f6",
        surface: "#f7faf9",
        "on-surface": "#253443",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#aebabb",
        error: "#b53d35",
        "on-error": "#fff8f7",
        "secondary-container": "#dcebf2",
      },
      fontFamily: {
        sans: ["Avenir Next", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
