#!/usr/bin/env python3

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shlex
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
IMAGE_REPOSITORY = "ghcr.io/lingengyuan/docflow"


def _run(args: list[str]) -> None:
    subprocess.run(args, cwd=ROOT, check=True)


def _project_version() -> str:
    with (ROOT / "pyproject.toml").open("rb") as handle:
        payload = tomllib.load(handle)
    version = payload.get("project", {}).get("version")
    if not isinstance(version, str) or not version:
        raise RuntimeError("pyproject.toml is missing [project].version")
    return version


def _git_output(args: list[str]) -> str:
    result = subprocess.run(args, cwd=ROOT, check=True, capture_output=True, text=True)
    return result.stdout.strip()


def _git_commit(explicit: str | None) -> str:
    if explicit:
        return explicit
    try:
        return _git_output(["git", "rev-parse", "--short=12", "HEAD"])
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def _source_dirty() -> bool:
    try:
        return bool(_git_output(["git", "status", "--short"]))
    except (OSError, subprocess.CalledProcessError):
        return True


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _build_package(dist_dir: Path, clean_dist: bool) -> None:
    if clean_dist:
        shutil.rmtree(dist_dir, ignore_errors=True)
    dist_dir.mkdir(parents=True, exist_ok=True)
    _run([sys.executable, "-m", "build", "--outdir", str(dist_dir)])


def _build_command(argv: list[str] | None) -> str:
    effective_argv = sys.argv[1:] if argv is None else argv
    return shlex.join(["python", "scripts/build_release_candidate.py", *effective_argv])


def _artifact_files(dist_dir: Path, version: str) -> list[Path]:
    files = [
        *dist_dir.glob(f"docflow-{version}-*.whl"),
        dist_dir / f"docflow-{version}.tar.gz",
    ]
    artifacts = [path for path in files if path.is_file()]
    suffixes = {path.suffix for path in artifacts}
    if ".whl" not in suffixes or not any(path.name.endswith(".tar.gz") for path in artifacts):
        raise RuntimeError(
            f"{dist_dir} must contain docflow {version} wheel and source archive artifacts"
        )
    return sorted(artifacts, key=lambda path: path.name)


def _image_tags(version: str) -> dict[str, list[str] | str]:
    major_minor = ".".join(version.split(".")[:2])
    return {
        "main_branch": f"{IMAGE_REPOSITORY}:edge",
        "release_tags": [
            f"{IMAGE_REPOSITORY}:{version}",
            f"{IMAGE_REPOSITORY}:{major_minor}",
            f"{IMAGE_REPOSITORY}:latest",
        ],
    }


def _release_notes(version: str, commit: str, manifest: dict[str, Any]) -> str:
    artifact_names = "\n".join(f"- `{item['file']}`" for item in manifest["artifacts"])
    release_tags = "\n".join(
        f"- `{tag}`" for tag in manifest["container_images"]["release_tags"]
    )
    return f"""# DocFlow v{version} Release Candidate

Commit: `{commit}`

## Install

- Docker image tags for a tagged release:
{release_tags}
- Python artifacts are attached to the GitHub release only. DocFlow is not published to PyPI yet.

## Python Artifacts

{artifact_names}

Verify the Python artifacts with `SHA256SUMS`.

## Validation

- Confirm GitHub CI, CodeQL, dependency audit, Docker image workflow, and
  OpenSSF Scorecard pass on the release commit.
- Confirm `docs/status.md` and README verification numbers match measured output.
- Confirm screenshots are current when the browser UI changed.

## Security Notes

- Docker image SBOM and provenance are generated by the Docker workflow.
- Release artifacts are not signed yet. Do not describe this release as signed.
- If PyPI publishing is enabled later, use Trusted Publishing rather than a long-lived token.

## Known Limitations

- DocFlow remains a local-first desktop browser workspace, not a hosted service.
- Full public benchmark coverage is still broader than the committed regression sets.
"""


def _write_checksums(dist_dir: Path, artifacts: list[Path]) -> Path:
    checksum = dist_dir / "SHA256SUMS"
    lines = [f"{_sha256(path)}  {path.name}" for path in artifacts]
    checksum.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return checksum


def build_release_candidate(
    *,
    dist_dir: Path,
    version: str,
    commit: str,
    clean_dist: bool,
    skip_build: bool,
    require_clean: bool,
    build_command: str,
) -> dict[str, Any]:
    dirty = _source_dirty()
    if require_clean and dirty:
        raise RuntimeError("release candidates must be built from a clean git working tree")

    if not skip_build:
        _build_package(dist_dir, clean_dist)

    artifacts = _artifact_files(dist_dir, version)
    checksum = _write_checksums(dist_dir, artifacts)
    artifact_payload = [
        {"file": path.name, "sha256": _sha256(path), "bytes": path.stat().st_size}
        for path in artifacts
    ]
    manifest: dict[str, Any] = {
        "schema": "docflow.release_candidate.v1",
        "version": version,
        "commit": commit,
        "build": {
            "command": build_command,
            "python": sys.version.split()[0],
            "platform": sys.platform,
            "github_run_id": os.environ.get("GITHUB_RUN_ID"),
            "github_run_attempt": os.environ.get("GITHUB_RUN_ATTEMPT"),
            "github_sha": os.environ.get("GITHUB_SHA"),
        },
        "source_tree": {"dirty": dirty},
        "artifacts": artifact_payload,
        "checksum_file": checksum.name,
        "release_notes_template": "RELEASE_NOTES.md",
        "container_images": {
            **_image_tags(version),
            "sbom": True,
            "provenance": True,
        },
        "pypi": {
            "published": False,
            "policy": "Do not claim PyPI availability until Trusted Publishing is configured.",
        },
        "signing": {
            "signed": False,
            "policy": "Do not call artifacts signed until a real signing flow is validated.",
        },
    }
    (dist_dir / "RELEASE_MANIFEST.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (dist_dir / "RELEASE_NOTES.md").write_text(
        _release_notes(version, commit, manifest),
        encoding="utf-8",
    )
    return manifest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Build or verify DocFlow release-candidate artifacts."
    )
    parser.add_argument("--dist-dir", type=Path, default=ROOT / "dist")
    parser.add_argument("--version", default=_project_version())
    parser.add_argument("--commit")
    parser.add_argument("--skip-build", action="store_true")
    parser.add_argument("--clean-dist", action="store_true")
    parser.add_argument("--require-clean", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)
    command = _build_command(argv)

    try:
        manifest = build_release_candidate(
            dist_dir=args.dist_dir,
            version=args.version,
            commit=_git_commit(args.commit),
            clean_dist=args.clean_dist,
            skip_build=args.skip_build,
            require_clean=args.require_clean,
            build_command=command,
        )
    except (OSError, RuntimeError, subprocess.CalledProcessError) as exc:
        print(f"Release candidate build failed: {exc}", file=sys.stderr)
        return 1

    if args.json:
        print(json.dumps(manifest, indent=2, sort_keys=True))
    else:
        print(f"Release candidate prepared for DocFlow {manifest['version']}")
        print(f"- {args.dist_dir / 'SHA256SUMS'}")
        print(f"- {args.dist_dir / 'RELEASE_MANIFEST.json'}")
        print(f"- {args.dist_dir / 'RELEASE_NOTES.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
